"use client";
import RoleRoute from "@/components/shared/RoleRoute";
import { becomeSellerApi, updateProfileApi } from "@/lib/authApi";
import { useAuth } from "@/providers/AuthProvider";
import { useMutation } from "@tanstack/react-query";
import { Save, Store } from "lucide-react";
import { useForm } from "react-hook-form";
import toast from "react-hot-toast";

export default function ProfilePage() {
  const { user, refreshUser } = useAuth();
  const { register, handleSubmit } = useForm({ values: { name: user?.name || "", phone: user?.phone || "", location: user?.location || "", photo: user?.photo || user?.image || "" } });
  const updateMutation = useMutation({ mutationFn: updateProfileApi, onSuccess: async data => { toast.success(data.message || "Profile updated."); await refreshUser(); }, onError: error => toast.error(error?.response?.data?.message || error.message) });
  const becomeSellerMutation = useMutation({ mutationFn: becomeSellerApi, onSuccess: async data => { toast.success(data.message || "You are now a seller."); await refreshUser(); }, onError: error => toast.error(error?.response?.data?.message || error.message) });
  const handleBecomeSeller = () => { if (!user?.phone || !user?.location) return toast.error("Please add phone and location before becoming a seller."); becomeSellerMutation.mutate({ phone: user.phone, location: user.location }); };
  return <RoleRoute allowedRoles={["buyer", "seller", "admin"]}><div className="space-y-6"><div><p className="text-sm font-bold uppercase tracking-[0.25em] text-orange-500">Profile Settings</p><h1 className="mt-2 text-3xl font-black text-slate-950 dark:text-white">Manage your account</h1></div><div className="grid gap-6 lg:grid-cols-[0.7fr_1fr]"><div className="dashboard-card"><img src={user?.photo || user?.image || "https://i.pravatar.cc/160?img=12"} alt={user?.name || "User"} className="h-28 w-28 rounded-3xl object-cover"/><h2 className="mt-5 text-2xl font-black text-slate-950 dark:text-white">{user?.name}</h2><p className="text-slate-500">{user?.email}</p><p className="mt-4 inline-flex rounded-full bg-orange-100 px-4 py-1 text-sm font-bold capitalize text-orange-700 dark:bg-orange-500/10 dark:text-orange-300">{user?.role}</p>{user?.role === "buyer" && <button onClick={handleBecomeSeller} disabled={becomeSellerMutation.isPending} className="btn-primary mt-6 w-full"><Store size={18}/>Become Seller</button>}</div><form onSubmit={handleSubmit(data => updateMutation.mutate(data))} className="dashboard-card"><h2 className="mb-5 text-2xl font-black text-slate-950 dark:text-white">Update Profile</h2><div className="grid gap-5 md:grid-cols-2"><input placeholder="Name" className="rounded-2xl border border-slate-200 bg-white px-4 py-3 dark:border-slate-700 dark:bg-slate-950" {...register("name", { required: true })}/><input placeholder="Phone" className="rounded-2xl border border-slate-200 bg-white px-4 py-3 dark:border-slate-700 dark:bg-slate-950" {...register("phone")}/><input placeholder="Location" className="rounded-2xl border border-slate-200 bg-white px-4 py-3 dark:border-slate-700 dark:bg-slate-950" {...register("location")}/><input placeholder="Photo URL" className="rounded-2xl border border-slate-200 bg-white px-4 py-3 dark:border-slate-700 dark:bg-slate-950" {...register("photo")}/></div><button type="submit" disabled={updateMutation.isPending} className="btn-primary mt-6"><Save size={18}/>{updateMutation.isPending ? "Saving..." : "Save Changes"}</button></form></div></div></RoleRoute>;
}
