"use client";
import PublicLayout from "@/components/layout/PublicLayout";
import ProductCard from "@/components/products/ProductCard";
import SkeletonCard from "@/components/shared/SkeletonCard";
import { getFeaturedProductsApi, getProductCategoriesApi } from "@/lib/productsApi";
import { getMarketplaceStatsApi, getTrustedSellersApi } from "@/lib/statsApi";
import { useQuery } from "@tanstack/react-query";
import { motion } from "framer-motion";
import { ArrowRight, BadgeCheck, Leaf, ShieldCheck, ShoppingBag, Users } from "lucide-react";
import Link from "next/link";

const categoryIcons = { Electronics: "💻", "Mobile Phones": "📱", Furniture: "🛋️", Vehicles: "🚗", Fashion: "👕", "Home Appliances": "🏠" };

export default function HomePage() {
  const { data: featuredData, isLoading } = useQuery({ queryKey: ["featured-products"], queryFn: () => getFeaturedProductsApi({ limit: 8 }) });
  const { data: categoriesData } = useQuery({ queryKey: ["home-categories"], queryFn: getProductCategoriesApi });
  const { data: statsData } = useQuery({ queryKey: ["marketplace-stats"], queryFn: getMarketplaceStatsApi });
  const { data: trustedData } = useQuery({ queryKey: ["trusted-sellers"], queryFn: getTrustedSellersApi });
  const products = featuredData?.products || []; const categories = categoriesData?.categories || ["Electronics", "Mobile Phones", "Furniture", "Vehicles", "Fashion"]; const stats = statsData?.stats || {}; const trustedSellers = trustedData?.sellers || [];
  return <PublicLayout><main className="bg-slate-50 dark:bg-slate-950">
    <section className="mx-auto grid max-w-7xl gap-10 px-4 py-16 lg:grid-cols-[1.1fr_0.9fr] lg:items-center"><motion.div initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }}><p className="mb-4 text-sm font-bold uppercase tracking-[0.3em] text-orange-500">Sustainable Marketplace</p><h1 className="text-5xl font-black leading-tight text-slate-950 dark:text-white md:text-7xl">Buy smarter. Sell faster. Reuse better.</h1><p className="mt-6 max-w-2xl text-lg text-slate-600 dark:text-slate-300">Discover affordable second-hand products from trusted sellers and complete secure purchases through ReSell Hub.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/products" className="btn-primary">Browse Products<ArrowRight size={18}/></Link><Link href="/register" className="btn-secondary">Start Selling</Link></div><div className="mt-10 grid gap-4 sm:grid-cols-3">{[{ label: "Products", value: stats.totalProducts || 0 }, { label: "Sellers", value: stats.totalSellers || 0 }, { label: "Buyers", value: stats.totalBuyers || 0 }].map(item => <div key={item.label} className="rounded-3xl bg-white p-5 shadow-sm dark:bg-slate-900"><p className="text-3xl font-black text-orange-600">{item.value}</p><p className="text-sm font-semibold text-slate-500">{item.label}</p></div>)}</div></motion.div><motion.div initial={{ opacity: 0, scale: 0.96 }} animate={{ opacity: 1, scale: 1 }} className="rounded-[2rem] bg-slate-950 p-5 shadow-xl"><img src="https://images.unsplash.com/photo-1556742502-ec7c0e9f34b1?q=80&w=1400&auto=format&fit=crop" alt="Marketplace" className="aspect-[4/3] rounded-[1.5rem] object-cover"/><div className="mt-5 grid gap-4 sm:grid-cols-3">{[{ icon: ShieldCheck, label: "Secure" }, { icon: BadgeCheck, label: "Verified Sellers" }, { icon: Leaf, label: "Eco Friendly" }].map(item => { const Icon = item.icon; return <div key={item.label} className="rounded-2xl bg-white/10 p-4 text-center text-white"><Icon className="mx-auto text-orange-400"/><p className="mt-2 text-sm font-bold">{item.label}</p></div>; })}</div></motion.div></section>
    <section className="mx-auto max-w-7xl px-4 py-12"><div className="mb-7 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-sm font-bold uppercase tracking-[0.25em] text-orange-500">Featured Products</p><h2 className="mt-2 text-4xl font-black text-slate-950 dark:text-white">Fresh marketplace picks</h2></div><Link href="/products" className="btn-secondary">View All Products</Link></div>{isLoading ? <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{Array.from({ length: 8 }).map((_, i) => <SkeletonCard key={i}/>)}</div> : products.length === 0 ? <div className="rounded-3xl bg-white p-10 text-center font-semibold text-slate-500 dark:bg-slate-900">No featured products yet. Approve products from admin dashboard.</div> : <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{products.map(product => <ProductCard key={product._id} product={product}/>)}</div>}</section>
    <section className="mx-auto max-w-7xl px-4 py-12"><div className="rounded-[2rem] bg-white p-8 shadow-sm dark:bg-slate-900"><p className="text-sm font-bold uppercase tracking-[0.25em] text-orange-500">Popular Categories</p><h2 className="mt-2 text-4xl font-black text-slate-950 dark:text-white">Browse by category</h2><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{categories.slice(0, 5).map(category => <Link key={category} href={`/products?category=${encodeURIComponent(category)}`} className="rounded-3xl bg-slate-50 p-6 text-center transition hover:-translate-y-1 hover:bg-orange-50 dark:bg-slate-950 dark:hover:bg-orange-500/10"><p className="text-4xl">{categoryIcons[category] || "🛍️"}</p><p className="mt-3 font-black text-slate-950 dark:text-white">{category}</p></Link>)}</div></div></section>
    <section className="mx-auto grid max-w-7xl gap-6 px-4 py-12 lg:grid-cols-3">{[{ icon: Leaf, title: "Sustainability Impact", text: "Buying second-hand reduces waste and gives products a longer life." }, { icon: ShieldCheck, title: "Safe Marketplace", text: "Role-based dashboards, admin moderation, and secure payments protect users." }, { icon: ShoppingBag, title: "Success Stories", text: "Sellers can quickly list products and buyers can find affordable deals." }].map(item => { const Icon = item.icon; return <div key={item.title} className="dashboard-card"><Icon className="text-orange-500" size={32}/><h3 className="mt-5 text-2xl font-black text-slate-950 dark:text-white">{item.title}</h3><p className="mt-3 text-slate-600 dark:text-slate-300">{item.text}</p></div>; })}</section>
    <section className="mx-auto max-w-7xl px-4 py-12"><div className="rounded-[2rem] bg-slate-950 p-8 text-white"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-sm font-bold uppercase tracking-[0.25em] text-orange-400">Trusted Sellers</p><h2 className="mt-2 text-4xl font-black">Verified marketplace sellers</h2></div><Users className="text-orange-400" size={44}/></div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{trustedSellers.length === 0 ? <p className="text-slate-300">No verified sellers yet. Admin can verify sellers from user management.</p> : trustedSellers.map(seller => <div key={seller._id} className="rounded-3xl bg-white/10 p-5 backdrop-blur"><img src={seller.photo || seller.image || "https://i.pravatar.cc/120"} alt={seller.name} className="h-14 w-14 rounded-2xl object-cover"/><p className="mt-4 font-black">{seller.name}</p><p className="text-sm text-slate-300">{seller.email}</p></div>)}</div></div></section>
  </main></PublicLayout>;
}
