"use client";
import PublicLayout from "@/components/layout/PublicLayout";
import { getProductByIdApi } from "@/lib/productsApi";
import { useAuth } from "@/providers/AuthProvider";
import { useQuery } from "@tanstack/react-query";
import { BadgeCheck, ShoppingCart } from "lucide-react";
import Link from "next/link";
import { useParams } from "next/navigation";

export default function ProductDetailsPage() {
  const params = useParams(); const id = params.id; const { user } = useAuth();
  const { data, isLoading, isError } = useQuery({ queryKey: ["product", id], queryFn: () => getProductByIdApi(id), enabled: Boolean(id) });
  const product = data?.product;
  if (isLoading) return <PublicLayout><main className="min-h-screen bg-slate-50 px-4 py-20 text-center dark:bg-slate-950"><p className="font-semibold text-slate-600 dark:text-slate-300">Loading product...</p></main></PublicLayout>;
  if (isError || !product) return <PublicLayout><main className="min-h-screen bg-slate-50 px-4 py-20 text-center dark:bg-slate-950"><p className="font-semibold text-red-500">Product could not be loaded.</p></main></PublicLayout>;
  const isOwnProduct = user && String(product.sellerInfo?.userId) === String(user._id || user.id);
  return <PublicLayout><main className="min-h-screen bg-slate-50 px-4 py-10 dark:bg-slate-950"><div className="mx-auto grid max-w-6xl gap-8 lg:grid-cols-[1fr_0.8fr]"><div className="rounded-3xl bg-white p-5 shadow-sm dark:bg-slate-900"><img src={product.images?.[0]} alt={product.title} className="aspect-[4/3] w-full rounded-3xl object-cover"/>{product.images?.length > 1 && <div className="mt-4 grid grid-cols-4 gap-3">{product.images.slice(0, 4).map(image => <img key={image} src={image} alt={product.title} className="aspect-square rounded-2xl object-cover"/>)}</div>}</div><div className="rounded-3xl bg-white p-6 shadow-sm dark:bg-slate-900"><p className="text-sm font-bold uppercase tracking-[0.25em] text-orange-500">{product.category}</p><h1 className="mt-2 text-4xl font-black text-slate-950 dark:text-white">{product.title}</h1><p className="mt-3 text-3xl font-black text-orange-600">৳{Number(product.price).toLocaleString()}</p><p className="mt-5 text-slate-600 dark:text-slate-300">{product.description}</p><div className="mt-6 grid gap-4 md:grid-cols-2">{[["Condition", product.condition], ["Stock", product.stockQuantity], ["Location", product.location], ["Status", product.status]].map(([label, value]) => <div key={label} className="rounded-2xl bg-slate-50 p-4 dark:bg-slate-950"><p className="text-sm text-slate-500">{label}</p><p className="font-bold capitalize">{value}</p></div>)}</div><div className="mt-6 rounded-3xl border border-slate-200 p-5 dark:border-slate-800"><p className="text-sm text-slate-500">Seller</p><div className="mt-2 flex items-center justify-between gap-4"><div><p className="font-black text-slate-950 dark:text-white">{product.sellerInfo?.name}</p><p className="text-sm text-slate-500">{product.sellerInfo?.email}</p></div>{product.sellerInfo?.isVerifiedSeller && <span className="inline-flex items-center gap-1 rounded-full bg-green-100 px-3 py-1 text-sm font-bold text-green-700 dark:bg-green-500/10 dark:text-green-300"><BadgeCheck size={16}/>Verified</span>}</div></div>{product.status === "available" && !isOwnProduct && <Link href={`/checkout/${product._id}`} className="btn-primary mt-6 w-full"><ShoppingCart size={18}/>Buy Now</Link>}{isOwnProduct && <p className="mt-6 rounded-2xl bg-yellow-50 px-4 py-3 text-center text-sm font-bold text-yellow-700 dark:bg-yellow-500/10 dark:text-yellow-300">This is your own product. You cannot buy it.</p>}</div></div></main></PublicLayout>;
}
