"use client";
import { becomeSellerApi, loginWithGoogle, registerWithEmail } from "@/lib/authApi";
import { useAuth } from "@/providers/AuthProvider";
import { useMutation } from "@tanstack/react-query";
import { UserPlus } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useForm } from "react-hook-form";
import toast from "react-hot-toast";

export default function RegisterClient() {
  const router = useRouter(); const { refreshUser } = useAuth();
  const { register, handleSubmit, watch } = useForm({ defaultValues: { name: "", email: "", password: "", image: "", role: "buyer", phone: "", location: "" } });
  const selectedRole = watch("role");
  const registerMutation = useMutation({ mutationFn: async (formData) => { await registerWithEmail({ name: formData.name, email: formData.email, password: formData.password, image: formData.image }); await refreshUser(); if (formData.role === "seller") { await becomeSellerApi({ phone: formData.phone, location: formData.location }); await refreshUser(); } return true; }, onSuccess: () => { toast.success("Registration successful."); router.push("/dashboard"); }, onError: e => toast.error(e.message || "Registration failed.") });
  const googleMutation = useMutation({ mutationFn: loginWithGoogle, onError: e => toast.error(e.message || "Google login failed.") });
  return <main className="flex min-h-screen items-center justify-center bg-slate-50 px-4 py-10 dark:bg-slate-950"><div className="grid w-full max-w-5xl overflow-hidden rounded-[2rem] bg-white shadow-sm dark:bg-slate-900 lg:grid-cols-2"><div className="hidden bg-slate-950 p-10 text-white lg:block"><p className="text-sm font-bold uppercase tracking-[0.3em] text-orange-400">Join Marketplace</p><h1 className="mt-5 text-5xl font-black">Start buying or selling pre-owned products</h1><p className="mt-5 text-slate-300">Create an account as a buyer or seller.</p></div><div className="p-6 sm:p-10"><Link href="/" className="text-sm font-bold text-orange-600">← Back Home</Link><h2 className="mt-8 text-3xl font-black text-slate-950 dark:text-white">Create your account</h2><form onSubmit={handleSubmit(data => registerMutation.mutate(data))} className="mt-7 space-y-4"><input placeholder="Full name" className="w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 dark:border-slate-700 dark:bg-slate-950" {...register("name", { required: true })}/><input type="email" placeholder="Email address" className="w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 dark:border-slate-700 dark:bg-slate-950" {...register("email", { required: true })}/><input type="password" placeholder="Password" className="w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 dark:border-slate-700 dark:bg-slate-950" {...register("password", { required: true, minLength: 6 })}/><input placeholder="Photo URL optional" className="w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 dark:border-slate-700 dark:bg-slate-950" {...register("image")}/><select className="w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 dark:border-slate-700 dark:bg-slate-950" {...register("role")}><option value="buyer">Register as Buyer</option><option value="seller">Register as Seller</option></select>{selectedRole === "seller" && <div className="grid gap-4 md:grid-cols-2"><input placeholder="Phone" className="rounded-2xl border border-slate-200 bg-white px-4 py-3 dark:border-slate-700 dark:bg-slate-950" {...register("phone", { required: selectedRole === "seller" })}/><input placeholder="Location" className="rounded-2xl border border-slate-200 bg-white px-4 py-3 dark:border-slate-700 dark:bg-slate-950" {...register("location", { required: selectedRole === "seller" })}/></div>}<button type="submit" disabled={registerMutation.isPending} className="btn-primary w-full"><UserPlus size={18}/>{registerMutation.isPending ? "Creating..." : "Create Account"}</button></form><button onClick={() => googleMutation.mutate()} disabled={googleMutation.isPending} className="btn-secondary mt-4 w-full">Continue with Google</button><p className="mt-6 text-center text-sm text-slate-500">Already have an account? <Link href="/login" className="font-bold text-orange-600">Login</Link></p></div></div></main>;
}
